name: "Push secrets from 1Password to Github Actions"

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - "demo-push-secrets-*"

jobs:
  demo-push-secrets:
    name: "Push Secret"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load GH token
        id: op-gh-token
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: op://pulumi/demo-soapy1-gh-token/credential

      - uses: pulumi/auth-actions@v1
        with:
          organization: soapy1
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:soapy1

      - uses: pulumi/actions@v6
        with:
          command: up
          refresh: true
          stack-name: dev
          work-dir: "./1p-write-secrets-demo-yaml"
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: ${{ steps.op-gh-token.outputs.GITHUB_TOKEN }}
